# Generated by Django 3.1.4 on 2021-02-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meme_page", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Categorie",
        ),
    ]
