# Generated by Django 3.1.4 on 2021-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meme_page", "0002_auto_20210215_1535"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorie",
            new_name="Genre",
        ),
    ]
