# Generated by Django 3.1.4 on 2021-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_page', '0007_auto_20210217_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='genres',
            field=models.ManyToManyField(default=None, null=True, to='meme_page.Genre'),
        ),
    ]
