# Generated by Django 3.1.4 on 2021-03-05 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meme_page', '0010_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
